
azure:
  keyvault:
    uri: https://amportfoliokeyvault.vault.azure.net/

spring:
  datasource:
    url: jdbc:sqlserver://amportfolio.database.windows.net:1433;database=amportfolionp;user=am@amportfolio;password=@M1unish;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: am@amportfolio
    password: "@M1unish"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update  # Automatically create or update tables
    show-sql: true  # Shows SQL statements in the console
    properties:
      hibernate:
        format_sql: true