
azure:
  keyvault:
    uri: https://amportfoliokeyvault.vault.azure.net/

spring:
  datasource:
    url: ${sqlconnectionstring}
    username: ${dbusername}
    password: ${dbpassword}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update  # Automatically create or update tables
    show-sql: true  # Shows SQL statements in the console
    properties:
      hibernate:
        format_sql: true
