# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true

# Spring MVC configuration
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true

# Logging configuration
logging.level.org.springframework.web.servlet.mvc=TRACE
logging.level.org.springframework.web.servlet.view=TRACE
logging.level.org.springframework.web.servlet.handler=TRACE

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/myportfoliodb
spring.datasource.username=myportfoliouser
spring.datasource.password=myportfoliopass

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true