# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true

# Spring MVC configuration
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true

# Logging configuration
logging.level.org.springframework.web.servlet.mvc=TRACE
logging.level.org.springframework.web.servlet.view=TRACE
logging.level.org.springframework.web.servlet.handler=TRACE