
azure:
  keyvault:
    uri: https://amportfoliokeyvault.vault.azure.net/

spring:
  application:
    name: stock-data
  datasource:
     url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true
     username: sa
     password: "XXXXXXX"
     driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
